"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

import { useGame } from "ecctrl";
import { useFrame } from "@react-three/fiber";
type GLTFResult = GLTF & {
  nodes: {
    Chapeau: THREE.SkinnedMesh;
    root: THREE.Bone;
  };
  materials: {
    ["color_main.014"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "course_chapeau" | "pose_chapeau";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Character(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf",
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  useGame((e) => (e.animations = actions));

  useGame((e) => {
    console.log(e);
  });
  return (
    <group
      ref={group}
      scale={4}
      position={[0, -0.7, 0]}
      {...props}
      dispose={null}
    >
      <group rotation={[0, 0.01, 0]}>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Chapeau.geometry}
          material={materials["color_main.014"]}
          skeleton={nodes.Chapeau.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/korrigan-hat/model.gltf",
);
